### ISSUE TITLE
Can't figure out how to get it to work

### ISSUE THREAD

**Issue by sjk210** [boarbox/randomizer-plus-plus#8]
Hello! I found this mod while trying to find a good randomizer mod for minecraft. This mod seems to be what I am looking for as other mods are usually just a timer that gives random blocks rather than randomizing the loot tables for blocks. The problem is that I cannot seem to figure out how to get the mod working. When loading into a new world nothing is randomized. I found the command and was trying to get it to work but everthing I do errors the command, giving me the message "The range of the random value must be at least 2" or just giving me the incomplete command error. Any tips on what to do would be appreciated! And thank you for making this mod!

**Comment by boarbox** [comment]
I haven't had time to sit down with this mod for a bit due to being busy. I'll have to refresh my memory but could you provide screenshots and the specific command you are trying to to run?

**Comment by sjk210** [comment]
![image](https://github.com/boarbox/randomizer-plus-plus/assets/27789404/4a36044b-71bf-40d9-bd5a-849ac1587cd6)
![image](https://github.com/boarbox/randomizer-plus-plus/assets/27789404/fc5d53fb-9dbd-4b92-a028-a50dfa7493c2)
These two (no matter what block I put it is the same error message). Honestly I was just messing with the commands because nothing was being randomized and I didnt know if I needed to do one of these commands to get it working.

**Comment by boarbox** [comment]
That command is actually vanilla, see [here](https://minecraft.wiki/w/Commands/random).

At the moment, the mod doesn't have any commands. You have to enable the randomizer when creating a new world. There should be a "Randomizer" tab added to the top of the screen.

I just moved so I can't provide screenshots right now, as my PC isn't setup yet.

The mod is still in the very early stage of development, so I welcome any feedback.

Hope this helps

**Comment by sjk210** [comment]
Oh shoot sorry lol. I don't even know how I missed that! Thank you very much.
